[package]
name = "mindblown"
version = "0.2.0"
description = "A brainf**k to x86 ELF compiler written in Rust meant for Linux and Windows under WSL."
license = "MIT"
edition = "2021"

[dependencies]
snailquote = "0.3.1"
rand = "0.8.5"

[profile.release]
lto = true
panic = "abort"
opt-level = 2